#!/usr/bin/env bash
# =============================================================================
#  run.sh — AI Engineer Portfolio: One-click setup and launch
#
#  What this does:
#    1. Checks system prerequisites (Python 3.10+, Node 18+, npm)
#    2. Creates .env files with your API keys (first run only)
#    3. Installs all Python and Node dependencies for every project
#    4. Starts all backends and frontends on fixed ports
#    5. Prints a clean summary table with every URL
#    6. Ctrl-C cleanly stops everything
#
#  Usage:
#    chmod +x run.sh
#    ./run.sh
#
#  First run will ask for your API keys once and save them.
#  Subsequent runs skip the key prompt if .env files already exist.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
LOG_DIR="$ROOT/.logs"
mkdir -p "$LOG_DIR"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

# ── Helpers ───────────────────────────────────────────────────────────────────
info()    { echo -e "${CYAN}[run.sh]${NC} $*"; }
ok()      { echo -e "${GREEN}[  OK  ]${NC} $*"; }
warn()    { echo -e "${YELLOW}[ WARN ]${NC} $*"; }
fail()    { echo -e "${RED}[ FAIL ]${NC} $*"; exit 1; }
section() { echo -e "\n${BOLD}━━━  $*  ━━━${NC}"; }

PIDS=()   # "pid:name" entries for cleanup

start_bg() {
  local name="$1"; shift
  local log="$LOG_DIR/${name}.log"
  info "Starting ${BOLD}${name}${NC} ..."
  "$@" >> "$log" 2>&1 &
  PIDS+=("$!:$name")
  ok "${name}  →  PID=$!  log=${log}"
}

cleanup() {
  echo ""
  section "SHUTTING DOWN"
  for entry in "${PIDS[@]:-}"; do
    local pid="${entry%%:*}" name="${entry##*:}"
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null && info "Stopped ${name} (PID ${pid})"
    fi
  done
  exit 0
}
trap cleanup SIGINT SIGTERM

# =============================================================================
#  1. PREREQUISITES
# =============================================================================
section "CHECKING PREREQUISITES"

# Python 3.10+
if ! command -v python3 &>/dev/null; then
  fail "Python 3 not found. Install from https://www.python.org/downloads/"
fi
PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 9 ]; }; then
  fail "Python 3.9+ required (found $PY_VER). Upgrade at https://www.python.org/downloads/"
fi
ok "Python $PY_VER"

# Node 18+
if ! command -v node &>/dev/null; then
  fail "Node.js not found. Install from https://nodejs.org (v18+)"
fi
NODE_VER=$(node -v | sed 's/v//')
NODE_MAJOR=$(echo "$NODE_VER" | cut -d. -f1)
if [ "$NODE_MAJOR" -lt 18 ]; then
  fail "Node 18+ required (found $NODE_VER). Upgrade at https://nodejs.org"
fi
ok "Node v$NODE_VER"

# npm
if ! command -v npm &>/dev/null; then
  fail "npm not found. It should come with Node.js."
fi
ok "npm $(npm -v)"

# =============================================================================
#  2. API KEY SETUP (first run only)
# =============================================================================
section "API KEY SETUP"

ENV_EXAMPLE="$ROOT/.env.example"
ROOT_ENV="$ROOT/.env"

if [ ! -f "$ROOT_ENV" ]; then
  echo ""
  echo -e "${YELLOW}No .env file found. Enter your API keys to continue.${NC}"
  echo -e "(Keys are saved locally in .env — never committed to git)\n"

  read -rp "  OpenAI API Key   (sk-...): " OPENAI_KEY
  echo ""
  read -rp "  DeepSeek API Key (sk-...): " DEEPSEEK_KEY
  echo ""

  cat > "$ROOT_ENV" <<EOF
# Auto-generated by run.sh — DO NOT COMMIT
OPENAI_API_KEY=${OPENAI_KEY}
DEEPSEEK_API_KEY=${DEEPSEEK_KEY}
EOF
  ok "API keys saved to .env"
else
  ok ".env already exists — skipping key prompt"
fi

# Load keys into environment
set -a; source "$ROOT_ENV"; set +a

# =============================================================================
#  3. PROPAGATE .env TO EACH PROJECT
# =============================================================================
section "PROPAGATING ENV FILES"

propagate_env() {
  local dest="$1"
  if [ ! -f "$dest/.env" ]; then
    cp "$ROOT_ENV" "$dest/.env"
    ok "Created $dest/.env"
  else
    ok "Exists  $dest/.env"
  fi
}

propagate_env "$ROOT/astro-intel-backend"
propagate_env "$ROOT/langchain_project"
propagate_env "$ROOT/langraph_project"
propagate_env "$ROOT/agentic-growth-os/backend"
propagate_env "$ROOT/ai-report-app/backend"
propagate_env "$ROOT/bench-resource-optimizer/backend"

# =============================================================================
#  4. INSTALL PYTHON DEPENDENCIES
# =============================================================================
section "INSTALLING PYTHON DEPENDENCIES"

setup_python() {
  local dir="$1" name="$2"
  info "Setting up Python venv: ${name}"
  # Recreate venv if it exists but pip has a broken shebang (moved directory)
  if [ -d "$dir/venv" ] && ! "$dir/venv/bin/pip" --version &>/dev/null; then
    warn "${name}: stale venv detected — recreating"
    rm -rf "$dir/venv"
  fi
  if [ ! -d "$dir/venv" ]; then
    python3 -m venv "$dir/venv"
  fi
  "$dir/venv/bin/pip" install --upgrade pip -q
  if [ -f "$dir/requirements.txt" ]; then
    "$dir/venv/bin/pip" install -r "$dir/requirements.txt" -q
    ok "${name} dependencies installed"
  else
    warn "${name}: no requirements.txt found"
  fi
}

setup_python "$ROOT/astro-intel-backend"        "astro-intel-backend"
setup_python "$ROOT/langchain_project"          "langchain-project"
setup_python "$ROOT/langraph_project"           "langraph-project"
setup_python "$ROOT/agentic-growth-os/backend"  "agentic-growth-os-backend"
setup_python "$ROOT/ai-report-app/backend"      "ai-report-app-backend"
setup_python "$ROOT/bench-resource-optimizer/backend" "bench-resource-optimizer-backend"

# =============================================================================
#  5. INSTALL NODE DEPENDENCIES
# =============================================================================
section "INSTALLING NODE DEPENDENCIES"

setup_node() {
  local dir="$1" name="$2"
  if [ -f "$dir/package.json" ]; then
    info "npm install: ${name}"
    (cd "$dir" && npm install --silent --legacy-peer-deps)
    ok "${name} node_modules ready"
  fi
}

# Detect correct Angular serve flag for this project
ng_serve_cmd() {
  local dir="$1" port="$2"
  local ng_version
  ng_version=$(node -e "try{const p=require('$dir/node_modules/@angular/cli/package.json');console.log(parseInt(p.version))}catch(e){console.log(0)}" 2>/dev/null)
  if [ "${ng_version:-0}" -ge 19 ]; then
    # Angular 19+ removed --disable-host-check
    echo "npx ng serve --port $port"
  else
    echo "npx ng serve --port $port --disable-host-check"
  fi
}

setup_node "$ROOT/astro-intel"                          "astro-intel"
setup_node "$ROOT/langchain_project/frontend"           "langchain-project-frontend"
setup_node "$ROOT/langraph_project/frontend"            "langraph-project-frontend"
setup_node "$ROOT/agentic-growth-os/frontend"           "agentic-growth-os-frontend"
setup_node "$ROOT/ai-report-app/frontend"               "ai-report-app-frontend"
setup_node "$ROOT/bench-resource-optimizer/frontend"    "bench-resource-optimizer-frontend"
setup_node "$ROOT/graph-visualizer"                     "graph-visualizer"

# =============================================================================
#  6. START BACKENDS
# =============================================================================
section "STARTING BACKENDS"

# Astro-Intel Backend → port 8080
start_bg "astro-intel-backend" \
  bash -c "cd '$ROOT/astro-intel-backend' && source venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"

# LangChain Project Backend → port 8080
start_bg "langchain-backend" \
  bash -c "cd '$ROOT/langchain_project' && source venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"

# LangGraph Project Backend → port 8001
start_bg "langraph-backend" \
  bash -c "cd '$ROOT/langraph_project' && source venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"

# Agentic Growth OS Backend → port 8002
start_bg "agentic-growth-os-backend" \
  bash -c "cd '$ROOT/agentic-growth-os/backend' && source venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8002 --reload"

# AI Report App Backend → port 8003
start_bg "ai-report-app-backend" \
  bash -c "cd '$ROOT/ai-report-app/backend' && source venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8003 --reload"

# Bench Resource Optimizer Backend → port 8004
start_bg "bench-resource-optimizer-backend" \
  bash -c "cd '$ROOT/bench-resource-optimizer/backend' && source venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8004 --reload"

info "Waiting 5s for backends to bind ..."
sleep 5

# =============================================================================
#  7. START FRONTENDS
# =============================================================================
section "STARTING FRONTENDS"

# Astro-Intel Frontend → port 4200
start_bg "astro-intel-frontend" \
  bash -c "cd '$ROOT/astro-intel' && $(ng_serve_cmd '$ROOT/astro-intel' 4200)"

# LangChain Project Frontend → port 4201
start_bg "langchain-frontend" \
  bash -c "cd '$ROOT/langchain_project/frontend' && $(ng_serve_cmd '$ROOT/langchain_project/frontend' 4201)"

# LangGraph Project Frontend → port 4202
start_bg "langraph-frontend" \
  bash -c "cd '$ROOT/langraph_project/frontend' && $(ng_serve_cmd '$ROOT/langraph_project/frontend' 4202)"

# Agentic Growth OS Frontend → port 4203
start_bg "agentic-growth-os-frontend" \
  bash -c "cd '$ROOT/agentic-growth-os/frontend' && $(ng_serve_cmd '$ROOT/agentic-growth-os/frontend' 4203)"

# AI Report App Frontend → port 4204
start_bg "ai-report-app-frontend" \
  bash -c "cd '$ROOT/ai-report-app/frontend' && $(ng_serve_cmd '$ROOT/ai-report-app/frontend' 4204)"

# Bench Resource Optimizer Frontend → port 4205
start_bg "bench-resource-optimizer-frontend" \
  bash -c "cd '$ROOT/bench-resource-optimizer/frontend' && $(ng_serve_cmd '$ROOT/bench-resource-optimizer/frontend' 4205)"

# Graph Visualizer → port 4206
start_bg "graph-visualizer" \
  bash -c "cd '$ROOT/graph-visualizer' && $(ng_serve_cmd '$ROOT/graph-visualizer' 4206)"

# =============================================================================
#  8. SUMMARY
# =============================================================================
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  ALL SERVICES STARTED — AI Engineer Portfolio${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BOLD}  Project                      Frontend                   Backend (API)${NC}"
echo -e "  ──────────────────────────────────────────────────────────────────────"
echo -e "  AstroIntel 360°              http://localhost:4200      http://localhost:8000/docs"
echo -e "  LangChain AI Service         http://localhost:4201      http://localhost:8080/docs"
echo -e "  LangGraph Agent System       http://localhost:4202      http://localhost:8001/docs"
echo -e "  Agentic Growth OS            http://localhost:4203      http://localhost:8002/docs"
echo -e "  AI Report App                http://localhost:4204      http://localhost:8003/docs"
echo -e "  Bench Resource Optimizer     http://localhost:4205      http://localhost:8004/docs"
echo -e "  Graph Visualizer             http://localhost:4206      (no backend)"
echo ""
echo -e "  Note: Angular frontends take 30-60s to compile on first start."
echo ""
echo -e "  Logs: ${LOG_DIR}/"
echo -e "  Press ${BOLD}Ctrl-C${NC} to stop all services."
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Wait for all background processes
wait
