import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from swot import swot

D = [
("ch01","Chapter 1 — Mind and Psychology",
 ["Observer/observed split, 2,500 years before clinical psychology",
  "Attention training with extraordinary adherence",
  "Wandering mind treated as ordinary, not personal failure",
  "Citta, manas, buddhi, ahamkara: distinctions English collapses"],
 ["Technique manuals are later (Yoga Sutras), not Vedic",
  "'5,000-year-old technique' claims are marketing, not history",
  "No mechanism, so no way to test what works"],
 ["Mindfulness now in clinical guidelines worldwide",
  "Free, equipment-free intervention at population scale",
  "Reframes distractibility as human, not defective"],
 ["Spiritual framing delays psychiatric treatment",
  "Karma converts illness into earned fault",
  "'Detachment' misused to suppress grief and anger",
  "Commercial capture: rigour gone, vocabulary priced"],
 "images/ch01-swot.png"),

("ch02","Chapter 2 — Body and Physiology",
 ["Solar-rhythm daily structure, confirmed by chronobiology",
  "Breath as accessible autonomic intervention",
  "Daily ritual solves the adherence problem",
  "Large body of knowledge on eating well without meat"],
 ["Atharvaveda fuses remedy and charm, undistinguished",
  "No controlled comparison, so failures never discarded",
  "Ascetic practice damaged bodies for prestige"],
 ["Time-restricted eating and circadian science now mainstream",
  "Low-cost practices for populations without clinicians",
  "Plant-forward food culture borrowed for climate and cost"],
 ["Purity rules exclude and kill (menstrual seclusion)",
  "'Ancient therefore effective' sells untested products",
  "Diaspora kept the food, lost the rhythm: metabolic cost"],
 "images/ch02-swot.png"),

("ch03","Chapter 3 — Finance and Wealth",
 ["Prosperity licensed as a legitimate human aim (artha)",
  "Rigveda 10.117: hoarded wealth is fragile, given wealth durable",
  "Dana as structural obligation, not optional charity",
  "A stopping rule: build in the middle, release at the end"],
 ["Trivarga had three aims; moksha is a late addition",
  "Fourfold scheme is Dharmashastra and epic, not Vedic",
  "Renunciation outranked production"],
 ["Framework that licenses building without spiritual apology",
  "Philanthropy rates that puzzle Western observers",
  "An answer to 'what is the number for?'"],
 ["Artha fused to caste: prosperity licensed by birth",
  "Karma used to justify poverty and block redistribution",
  "Stopping rule assumed a village that no longer exists",
  "Prosperity gospel quoting the framework it inverts"],
 "images/ch03-swot.png"),

("ch04","Chapter 4 — Work and Purpose",
 ["Work as offering: meaning in execution, not outcome",
  "Rigveda 9.112 shows plural trades in one household",
  "Detachment from result as durable working method",
  "Work placed inside life, not as container for all meaning"],
 ["Svadharma doctrine is Gita and Dharmashastra, not Samhita",
  "Ordered function later hardened into fixed-at-birth",
  "Craft lineage preserved technique by restricting entry"],
 ["Protects identity against job loss",
  "Answers the 'meaningful work' question without a promotion",
  "Available on identical terms to every occupation"],
 ["Birth doctrine made mobility a spiritual failure",
  "Sanctified degrading labour as assigned duty",
  "'Do not seek the fruit' used to suppress wage demands",
  "Producers ranked below interpreters who did the ranking"],
 "images/ch04-swot.png"),

("ch05","Chapter 5 — Family and Relationships",
 ["Household as ritual unit: obligation guarantees presence",
  "Marriage grounded in function, so it survives feeling's absence",
  "Pitr rites make individual death bearable",
  "Elder care as default, without institutions"],
 ["Dense obligation, almost no confidentiality",
  "Later rules (widow remarriage, property) are not Vedic",
  "Roles assigned; poor fit for those outside them"],
 ["Solves loneliness, now a measurable mortality risk",
  "Diaspora version: obligation kept by choice, exit available",
  "Continuity as meaning without requiring metaphysics"],
 ["Care costs invoiced almost entirely to women",
  "Endogamy is the actual enforcement arm of caste",
  "Pressure on those who do not fit has a body count",
  "Forty-one people in the group, nowhere to put the truth"],
 "images/ch05-swot.png"),

("ch06","Chapter 6 — Women and Gender",
 ["Women recorded as seers in a sacred canon",
  "Transmitters could have reassigned those hymns; they did not",
  "Rigveda 10.85 addresses the bride as household mistress",
  "The corpus supplies reformers their strongest argument"],
 ["Attribution is Anukramani, later than the hymns",
  "Later layers close ritual roles the early ones left open",
  "Interpretation passed into male hands for most of history"],
 ["Diaspora reads the text without village enforcement",
  "'On whose authority was that stopped?' has no good answer",
  "Education reform has always used the tradition's own texts"],
 ["Selective quotation: the text became a quarry",
  "Exclusion from Sanskrit meant exclusion from checking",
  "Purity apparatus attached to women's bodies still kills",
  "Restriction carries the corpus's authority; openness reads as curiosity"],
 "images/ch06-swot.png"),

("ch07","Chapter 7 — Social Order and Caste",
 ["Language of interdependence: one body, four parts",
  "Occupation as function in the early hymns",
  "The tradition preserved the evidence against its own misuse"],
 ["Fourfold order appears in exactly one hymn of over a thousand",
  "'Shudra' occurs nowhere else in the Rigveda",
  "Late diction (Muir, 1868) betrays a younger verse",
  "No text explains or defends the hierarchy it introduces"],
 ["Dating the verse dissolves its claim to be foundational",
  "Diaspora can read 10.90 without village enforcement",
  "Reform is strongest when drawn from the corpus itself"],
 ["Reverence made the text unarguable",
  "Untouchability built later, attributed backwards",
  "Self-sealing: those harmed were barred from reading it",
  "Endogamy persists in diaspora, unspoken not abolished"],
 "images/ch07-swot.png"),

("ch08","Chapter 8 — Knowledge and Learning",
 ["Redundant encoding: a checksum in human memory",
  "Shiksha phonetics as a defined encoding standard",
  "Proof that trained memory far exceeds modern assumptions",
  "Guru-shishya: sustained individual attention, the best-evidenced pedagogy"],
 ["Knowledge moved only through approved teachers",
  "Exact reproduction rewarded above new inquiry",
  "Orality kept the text pristine and scarce by design"],
 ["The preserved evidence makes this book's arguments possible",
  "A tested model for lossless transmission across millennia",
  "Rote discipline still yields world-class technical talent"],
 ["Precision and exclusivity were the same property",
  "Recitation without comprehension created interpreter dependence",
  "That dependence is how claims not in the text were attributed to it",
  "Reproduction without transfer is still the failure mode"],
 "images/ch08-swot.png"),

("ch09","Chapter 9 — Language and Expression",
 ["Panini's Ashtadhyayi: first rigorous grammar of any language",
  "Rule-ordering anticipates modern formal grammars",
  "Morphology built for technical precision",
  "Working language of maths, medicine, law and logic for a millennium"],
 ["Sacred language is a restricted language",
  "Sound-over-sense produced custody without access",
  "Prestige ranking demoted every living Indian language"],
 ["Sparked comparative philology and modern linguistics",
  "Sound-first transmission is why the Gayatri survives diaspora loss",
  "English now a link language belonging to no single region"],
 ["Sanskrit gate enforced the exclusions of Chapters 6, 7 and 8",
  "English replaced the gate rather than removing it",
  "Mother tongue lost by the third generation abroad",
  "Prayer survives; understanding of the prayer does not"],
 "images/ch09-swot.png"),

("ch10","Chapter 10 — Geography and Migration",
 ["Portable ritual: fire, water, materials, a person who knows",
  "Tradition stored in memory, so indenture could not confiscate it",
  "Sacred geography is distributive; new rivers can be sacralised",
  "Ritual calendar supplied infrastructure where nothing else existed"],
 ["Sea-crossing ban is Dharmashastra, absent from Vedic material",
  "Diaspora practice freezes at the emigration period",
  "Identity markers resist revision under pressure"],
 ["Enforcement needed a village; indenture destroyed all three conditions",
  "What emerged was flatter than what left, and than what stayed",
  "Educated diaspora can check the texts directly"],
 ["The rule mainly prevented return, trapping people",
  "Caste reassembled in the colonies within two generations",
  "UK equalities law still treats caste as a live category",
  "Tradition reduced to cuisine and endogamy by generation four"],
 "images/ch10-swot.png"),

("ch11","Chapter 11 — Environment and Nature",
 ["Nature addressed in the second person, not as resource",
  "Sacred groves show measurable preserved biodiversity",
  "Low-consumption household template",
  "Cyclical time never produced nature-as-raw-material"],
 ["Atharvaveda 12.1 establishes relationship, not restraint in use",
  "Reverence without measurement, regulation or enforcement",
  "Ritual purity was never physical cleanliness"],
 ["Legal personhood for rivers, watched worldwide",
  "Sufficiency vocabulary now needed by high-consumption societies",
  "Real strength for Indian environmental movements"],
 ["The most worshipped river is among the most polluted",
  "The rites themselves are a pollution source",
  "Cleaning assigned to those the hierarchy calls contaminated",
  "Rta absorbs damage: cosmic order supplies no urgency"],
 "images/ch11-swot.png"),

("ch12","Chapter 12 — Health and Medicine",
 ["Systematic observational medicine, early and organised",
  "Sushruta's forehead-flap rhinoplasty entered Western practice",
  "Prevention at the centre: dinacharya, ritucharya",
  "Whole-person framing, adopted late by modern medicine"],
 ["Atharvaveda fuses remedy and charm with equal authority",
  "'Five thousand years old' is marketing; Charaka and Sushruta are far later",
  "No controlled comparison, so nothing could ever be discarded"],
 ["Genuine candidate compounds worth proper investigation",
  "Prevention emphasis modern systems still cannot deliver",
  "Large materia medica built over two millennia"],
 ["Rasa shastra preparations carry documented heavy metal toxicity",
  "Antiquity marketed as an evidence substitute",
  "Delayed treatment for treatable disease kills",
  "Undisclosed supplement interactions in diaspora patients"],
 "images/ch12-swot.png"),

("ch13","Chapter 13 — Ethics and Conflict",
 ["Situational ethic engages hard cases rules cannot anticipate",
  "Dharma-sankata names genuine moral dilemma",
  "No absolution offered; victors are not happy",
  "Moral positions settled by contest, not decree"],
 ["Developed ethics is epic and Gita, not Samhita",
  "No universal prohibitions to appeal to",
  "The corpus contains sanctioned violence and warrior duty"],
 ["Gandhian synthesis reshaped the twentieth century",
  "Re-exported to civil rights and resistance movements",
  "Tells the reader a dilemma is not personal failure"],
 ["Situational ethics bends to whoever defines the situation",
  "Role-based duty encodes inequality as morality",
  "'Duty without attachment' used to override conscience",
  "Selective quotation is most dangerous here"],
 "images/ch13-swot.png"),

("ch14","Chapter 14 — Meaning and Mortality",
 ["Rigveda 10.129 licenses doubt from inside scripture, permanently",
  "Death made bearable by making the individual non-central",
  "Meaning available without requiring belief",
  "Philosophy of mind as inquiry, not revelation"],
 ["Upanishads do not speak with one voice",
  "The coherent system is largely Shankara, 8th century CE",
  "Moksha is a late arrival in the scheme of human aims"],
 ["Travels with nothing: no priest, fire, village or language",
  "Legible to sceptics in any century",
  "The preserved evidence enables the tradition's own audit"],
 ["Interiority used to justify accepting material injustice",
  "Karma turned suffering into accounting",
  "Renunciation outranked those who built and paid",
  "Depth deployed to deflect scrutiny of real harm"],
 "images/ch14-swot.png"),
]

for cid, title, s, w, o, t, out in D:
    swot(title, s, w, o, t, out)
print("generated", len(D))
