"""creator profiles

Revision ID: 5ea6127f4035
Revises: 98e6e6e0ed6b
Create Date: 2026-07-08 14:22:19.912788
"""
from alembic import op
import sqlalchemy as sa


revision = '5ea6127f4035'
down_revision = '98e6e6e0ed6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_profiles',
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('voice_provider', sa.String(length=30), nullable=False),
    sa.Column('voice_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_provider', sa.String(length=30), nullable=False),
    sa.Column('avatar_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_required', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_profiles_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_profile_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(
            'fk_projects_creator_profile_id', 'creator_profiles', ['creator_profile_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_creator_profile_id', type_='foreignkey')
        batch_op.drop_column('creator_profile_id')

    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_profiles_owner_id'))

    op.drop_table('creator_profiles')
    # ### end Alembic commands ###
