"""training sessions, photo path, thumbnail instructions

Revision ID: 94813e212432
Revises: 5ea6127f4035
Create Date: 2026-07-08 19:09:44.995500
"""
from alembic import op
import sqlalchemy as sa


revision = '94813e212432'
down_revision = '5ea6127f4035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_sessions_profile_id'), ['profile_id'], unique=False)

    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('video_jobs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('thumbnail_instructions', sa.Text(), nullable=False, server_default='')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_jobs', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_instructions')

    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.drop_column('photo_path')

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_profile_id'))

    op.drop_table('training_sessions')
    # ### end Alembic commands ###
