"""
RAGless response composer.
Given a matched runbook and its ordered steps (from graph traversal),
composes a structured incident response — no hallucination possible
because every command comes verbatim from the database.
"""
from __future__ import annotations
import json
from typing import Optional
from utils.llm import call_llm
from database.runbooks_store import get_runbook
from database.graph_store import load_graph_from_db, get_graph_analysis
from graph.dependency_graph import get_execution_order, get_parallel_execution_plan

SYSTEM = """You are a senior SRE writing an incident response summary.
Given a runbook title, description, and the incident description,
write a brief 2-3 sentence triage summary that:
1. Confirms this runbook addresses the incident
2. States the estimated resolution time
3. Highlights the most critical first step

Be direct and technical. No fluff. Output plain text only."""


def compose_response(
    incident_text: str,
    runbook_id: int,
) -> dict:
    """
    Build a complete incident response from structured DB data + graph traversal.
    Commands are NEVER generated by LLM — always pulled from DB verbatim.
    """
    runbook = get_runbook(runbook_id)
    if not runbook:
        return {"error": f"Runbook {runbook_id} not found"}

    # Load live graph and get safe execution order
    G = load_graph_from_db(runbook_id)
    try:
        execution_order = get_execution_order(G)
        parallel_groups = get_parallel_execution_plan(G)
    except ValueError:
        # Fallback to simple step number order if cycle detected
        execution_order = [s["step_number"] for s in runbook["steps"]]
        parallel_groups = [[n] for n in execution_order]

    # Build ordered steps from DB — exact commands, no LLM generation
    step_map = {s["step_number"]: s for s in runbook["steps"]}
    ordered_steps = []
    for n in execution_order:
        if n in step_map:
            s = step_map[n]
            ordered_steps.append({
                "step_number": s["step_number"],
                "title": s["title"],
                "description": s["description"],
                "commands": s["commands"],      # verbatim from DB
                "expected_output": s["expected_output"],
                "is_optional": s["is_optional"],
                "timeout_seconds": s["timeout_seconds"],
                "depends_on": s["depends_on"],
            })

    # LLM writes triage summary only — not commands
    triage_summary = _generate_triage(
        incident_text,
        runbook["title"],
        runbook["description"],
        runbook["estimated_duration_minutes"],
        ordered_steps[0] if ordered_steps else None,
    )

    # Build parallel execution waves
    waves = []
    for i, group in enumerate(parallel_groups, start=1):
        wave_steps = [step_map[n] for n in group if n in step_map]
        waves.append({
            "wave": i,
            "can_run_in_parallel": len(group) > 1,
            "steps": [{"step_number": s["step_number"], "title": s["title"]} for s in wave_steps],
        })

    return {
        "runbook_id": runbook_id,
        "runbook_title": runbook["title"],
        "category": runbook["category"],
        "severity": runbook["severity"],
        "estimated_duration_minutes": runbook["estimated_duration_minutes"],
        "triage_summary": triage_summary,
        "prerequisites": runbook["prerequisites"],
        "execution_order": execution_order,
        "steps": ordered_steps,
        "parallel_execution_plan": waves,
        "rollback_steps": runbook["rollback_steps"],
        "total_steps": len(ordered_steps),
        "source": "database",   # commands come from DB, not LLM — auditable
    }


def _generate_triage(
    incident: str,
    title: str,
    description: str,
    duration: int,
    first_step: Optional[dict],
) -> str:
    first_cmd = ""
    if first_step and first_step.get("commands"):
        first_cmd = first_step["commands"][0]

    prompt = (
        f"Incident: {incident}\n"
        f"Runbook: {title}\n"
        f"Runbook description: {description}\n"
        f"Estimated resolution time: {duration} minutes\n"
        f"First command to run: {first_cmd}"
    )
    try:
        return call_llm(SYSTEM, prompt, max_tokens=200)
    except Exception:
        return f"Apply runbook '{title}' to resolve this incident. Estimated time: {duration} minutes."
