"""
STEP 7 — Final Report Agent
Takes admin-approved sections and generates the polished final report.
"""
from __future__ import annotations
from datetime import datetime, timezone
from typing import Any, Dict, List


def final_report_agent(
    admin_review: Dict[str, Any],
    approved_ids: List[str],
    rejected_ids: List[str],
    brand_name: str = "{{BRAND_NAME}}",
    logo_url: str   = "{{LOGO_URL}}",
    image_url: str  = "{{IMAGE_URL}}",
    memory: Dict[str, Any] = {},
) -> Dict[str, Any]:

    all_sections = admin_review.get("sections", [])
    question     = admin_review.get("question","")
    focus        = admin_review.get("focus","general")
    subject      = admin_review.get("subject","")

    approved = [s for s in all_sections if s["id"] in approved_ids]
    rejected = [s["id"] for s in all_sections if s["id"] in rejected_ids]

    # Build module summary
    modules_used = [m for m in ["astrology","numerology","palmistry","tarot","vastu"] if m in memory]

    # Confidence distribution
    conf_dist = {"high": 0, "medium": 0, "low": 0}
    for s in approved:
        conf_dist[s.get("confidence","low")] += 1

    report = {
        "brand_name":   brand_name,
        "logo_url":     logo_url,
        "image_url":    image_url,
        "report_title": "360° Spiritual Intelligence Report",
        "user_name":    subject,
        "question":     question,
        "focus_area":   focus.capitalize(),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "modules_used": modules_used,
        "total_sections_reviewed":  len(all_sections),
        "total_sections_approved":  len(approved),
        "total_sections_rejected":  len(rejected),
        "confidence_distribution":  conf_dist,

        # ── TITLE PAGE ────────────────────────────────────────────────────────
        "title_page": {
            "brand":      brand_name,
            "logo_url":   logo_url,
            "image_url":  image_url,
            "title":      "360° Spiritual Intelligence Report",
            "subtitle":   "A comprehensive multi-discipline spiritual analysis",
            "for_person": subject,
            "question":   question,
            "date":       datetime.now(timezone.utc).strftime("%d %B %Y"),
            "modules":    modules_used,
        },

        # ── DISCLAIMER ────────────────────────────────────────────────────────
        "disclaimer": (
            "This report is prepared for spiritual guidance and personal reflection. "
            "All insights are expressed as tendencies and possibilities, not absolute predictions. "
            "This report does not replace professional medical, legal, or financial advice. "
            "All observations use probability language — 'suggests', 'tends toward', 'is indicated'."
        ),

        # ── APPROVED SECTIONS ─────────────────────────────────────────────────
        "sections": [
            {
                "id":         s["id"],
                "title":      s["title"],
                "content":    s["content"],
                "confidence": s["confidence"],
                "sources":    s.get("sources",[]),
                "approved":   True,
            }
            for s in approved
        ],

        # ── REJECTED SUMMARY ──────────────────────────────────────────────────
        "rejected_section_ids": rejected,

        # ── CLOSING NOTE ─────────────────────────────────────────────────────
        "closing_note": (
            f"This report was generated by {brand_name} — a 360° multi-tradition spiritual intelligence system. "
            "The insights presented here represent a synthesis of Vedic Astrology, Numerology, Palmistry, Tarot, and Vastu wisdom. "
            "Use this as a compass, not a map. Your choices and awareness remain the most powerful forces in your journey."
        ),
    }

    return report
