import { AfterViewInit, Component, ElementRef, OnDestroy, PLATFORM_ID, computed, inject, input, signal } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { LiveStatus } from './live-status.service';

/**
 * Each Engineering Proof card acts out its own claim: the LIVE card beats with the
 * real health check, the 66 card is one square per merged PR, the tests card runs
 * 637 dots green, and so on. Animations only play while the card is on screen.
 */
export interface MergedPr { repo: string; title: string; pr: string; }

export const REPO_COLOR: Record<string, string> = {
  'py-pdf/pypdf': '#86BC25', 'joblib/joblib': '#62B5E5', 'UKPLab/sentence-transformers': '#FFB81C',
  'huggingface/sentence-transformers': '#FFB81C', 'nltk/nltk': '#00ABAB', 'authlib/authlib': '#C084FC',
  'fonttools/fonttools': '#7C9CFF', 'py-pdf/fpdf2': '#F87171',
};

@Component({
  selector: 'proof-viz',
  standalone: true,
  host: { '[class.play]': 'playing()', '[class.calm]': 'calm' },
  template: `
    @switch (kind()) {
      @case ('SHIPPED') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <line x1="0" y1="40" x2="300" y2="40" class="pv-grid"/>
          <path class="pv-ekg" [class.down]="live.apiState() === 'down'" pathLength="1"
                d="M0 40 H70 L80 40 L88 22 L96 56 L104 10 L112 46 L120 40 H190 L200 40 L208 22 L216 56 L224 10 L232 46 L240 40 H300"/>
          <circle class="pv-beat" r="4" cy="40" [class.down]="live.apiState() === 'down'"/>
        </svg>
        <span class="pv-cap">{{ shippedCap() }}</span>
      }
      @case ('INTEGRATED') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          @for (a of apps; track a; let i = $index) {
            <text [attr.x]="0" [attr.y]="11 + i * 15" class="pv-lbl">{{ a }}</text>
            <path [attr.d]="'M58 ' + (7 + i * 15) + ' C150 ' + (7 + i * 15) + ' 170 32 232 32'" class="pv-wire"/>
            <circle r="2.6" class="pv-packet" [style.offset-path]="'path(\\'M58 ' + (7 + i * 15) + ' C150 ' + (7 + i * 15) + ' 170 32 232 32\\')'" [style.animation-delay]="i * 0.35 + 's'"/>
          }
          <rect x="232" y="18" width="66" height="28" rx="4" class="pv-hub"/>
          <text x="265" y="36" text-anchor="middle" class="pv-hub-t">1 engine</text>
        </svg>
      }
      @case ('TRUSTED') {
        <div class="pv-squares" role="list" aria-label="One square per merged pull request">
          @for (m of merges(); track m.pr; let i = $index) {
            <a role="listitem" class="pv-sq" [href]="m.pr" target="_blank" rel="noopener" [title]="m.repo + ': ' + m.title"
               [style.background]="color(m.repo)" [style.animation-delay]="i * 18 + 'ms'"></a>
          }
        </div>
        <span class="pv-cap">one square per merged PR · hover one</span>
      }
      @case ('FAST') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <text x="0" y="17" class="pv-lbl">before</text>
          <rect x="44" y="9" width="246" height="11" rx="2" class="pv-track"/>
          <rect x="44" y="9" width="246" height="11" rx="2" class="pv-bar slow"/>
          <text x="0" y="47" class="pv-lbl">after</text>
          <rect x="44" y="39" width="246" height="11" rx="2" class="pv-track"/>
          <rect x="44" y="39" width="246" height="11" rx="2" class="pv-bar fast"/>
        </svg>
        <span class="pv-cap">same request · 78 s before, 4 s after</span>
      }
      @case ('AFFORDABLE') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <text x="0" y="17" class="pv-lbl">GPT-4o</text>
          <rect x="52" y="9" width="238" height="11" rx="2" class="pv-bar cost-hi"/>
          <text x="0" y="47" class="pv-lbl">mine</text>
          <rect x="52" y="39" width="3" height="11" rx="1" class="pv-bar cost-lo"/>
          <text x="62" y="48" class="pv-note">÷ 500</text>
        </svg>
      }
      @case ('SAFE') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <rect x="0" y="16" width="52" height="32" rx="4" class="pv-hub"/>
          <text x="26" y="36" text-anchor="middle" class="pv-hub-t">SQL</text>
          @for (c of commands; track c; let i = $index) {
            <g class="pv-cmd" [style.animation-delay]="i * 1.1 + 's'">
              <text x="64" [attr.y]="14 + i * 19" class="pv-code">{{ c }}</text>
              <text x="296" [attr.y]="14 + i * 19" text-anchor="end" class="pv-ok">✓ verbatim</text>
            </g>
          }
        </svg>
        <span class="pv-cap">example runbook commands · generated by the model: 0</span>
      }
      @case ('SECURE') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <line x1="8" y1="30" x2="292" y2="30" class="pv-wire"/>
          @for (g of gates; track g; let i = $index) {
            <g class="pv-gate" [style.animation-delay]="0.5 + i * 0.5 + 's'">
              <rect [attr.x]="34 + i * 54" y="16" width="20" height="28" rx="3"/>
              <text [attr.x]="44 + i * 54" y="58" text-anchor="middle" class="pv-lbl">{{ g }}</text>
            </g>
          }
          <circle r="4" cy="30" class="pv-req"/>
          <circle r="4" cy="30" class="pv-bad"/>
        </svg>
        <span class="pv-cap">every response passes 5 gates · injections stop at G2</span>
      }
      @case ('RELIABLE') {
        <div class="pv-tests" aria-hidden="true">
          @for (t of tests; track t) { <i [style.animation-delay]="t * 6 + 'ms'"></i> }
        </div>
        <span class="pv-cap pv-count">{{ testCount() }} passed{{ testCount() === 637 ? ' · under 4 s' : '' }}</span>
      }
      @case ('ORCHESTRATED') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          @for (e of edges; track $index; let i = $index) {
            <path [attr.d]="e" class="pv-wire"/>
            <circle r="2.4" class="pv-packet" [style.offset-path]="'path(\\'' + e + '\\')'" [style.animation-delay]="(i % 3) * 0.25 + (i > 5 ? 1 : i > 2 ? 0.6 : 0) + 's'"/>
          }
          @for (n of nodes; track n.l) {
            <circle [attr.cx]="n.x" [attr.cy]="n.y" r="7" class="pv-node" [class.human]="n.l === 'human'"/>
            @if (!n.l.startsWith('agent')) { <text [attr.x]="n.x" [attr.y]="n.y + 19" text-anchor="middle" class="pv-lbl">{{ n.l }}</text> }
          }
        </svg>
        <span class="pv-cap">plan → 3 agents in parallel → merge → human approval → out</span>
      }

      @case ('STEPS') {
        @if (steps(); as st) {
          <svg [attr.viewBox]="'0 0 300 ' + (compact() ? 30 : 64)" class="pv" [class.pv-compact]="compact()" aria-hidden="true">
            <line [attr.x1]="st.w / 2" [attr.y1]="st.y" [attr.x2]="300 - st.w / 2" [attr.y2]="st.y" class="pv-wire"/>
            <circle r="3" class="pv-packet pv-packet-lin" [attr.cy]="0"
                    [style.offset-path]="st.path"
                    [style.animation-duration]="st.labels.length * 0.9 + 's'"/>
            @for (l of st.labels; track $index; let i = $index; let last = $last) {
              <g class="pv-step" [class.pv-step-live]="last && liveLast()" [style.animation-duration]="st.labels.length * 0.9 + 's'" [style.animation-delay]="i * 0.9 + 's'">
                <rect [attr.x]="i * (st.w + st.gap)" [attr.y]="st.y - st.h / 2" [attr.width]="st.w" [attr.height]="st.h" rx="3"/>
                <text [attr.x]="i * (st.w + st.gap) + st.w / 2" [attr.y]="st.y + 3.5" text-anchor="middle" class="pv-step-t">{{ l }}</text>
              </g>
            }
          </svg>
          @if (cap()) { <span class="pv-cap">{{ cap() }}</span> }
        }
      }
      @case ('AGENT') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <ellipse cx="150" cy="32" rx="118" ry="22" class="pv-wire"/>
          <circle r="3.4" class="pv-orbit"/>
          @for (l of loopLabels; track l; let i = $index) {
            <g class="pv-step" style="animation-duration: 3.6s" [style.animation-delay]="i * 0.9 + 's'">
              <rect [attr.x]="loopPos[i].x - 30" [attr.y]="loopPos[i].y - 9" width="60" height="18" rx="9"/>
              <text [attr.x]="loopPos[i].x" [attr.y]="loopPos[i].y + 3.5" text-anchor="middle" class="pv-step-t">{{ l }}</text>
            </g>
          }
        </svg>
        <span class="pv-cap">think → call a tool → observe → answer, until the task is done</span>
      }
      @case ('SECURITY') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <rect x="196" y="2" width="22" height="60" rx="3" class="pv-shield"/>
          <text x="207" y="36" text-anchor="middle" class="pv-shield-t">G</text>
          @for (r of inputs; track r.t; let i = $index) {
            <g class="pv-input" [class]="'pv-input ' + r.k" [style.animation-delay]="i * 1.2 + 's'">
              <text x="0" [attr.y]="12 + (i % 3) * 20" class="pv-code">{{ r.t }}</text>
              <text x="296" [attr.y]="12 + (i % 3) * 20" text-anchor="end" class="pv-verdict">{{ r.v }}</text>
            </g>
          }
        </svg>
        <span class="pv-cap">injection blocked · PII masked · the rest goes through</span>
      }
      @case ('MONTHS') {
        <div class="pv-months">
          @for (m of months(); track m.label) {
            <div class="pv-month">
              <div class="pv-stack" [style.height.%]="m.total / monthMax() * 100">
                @for (seg of m.segs; track seg.repo) {
                  <span [style.flex-grow]="seg.n" [style.background]="color(seg.repo)" [title]="seg.repo + ': ' + seg.n"></span>
                }
              </div>
              <b>{{ m.total }}</b>
              <small>{{ m.label }}</small>
            </div>
          }
        </div>
        <span class="pv-cap">merged PRs per month, coloured by library</span>
      }
      @case ('TENURE') {
        @if (tenure(); as t) {
          <div class="pv-tenure">
            <div class="pv-ten-track"><span class="pv-ten-bar" [style.width.%]="t.pct"></span></div>
            <span class="pv-ten-l">{{ t.label }}{{ t.present ? ' · and counting' : '' }}</span>
          </div>
        }
      }
    }
  `,
  styleUrl: './proof-viz.scss',
})
export class ProofViz implements AfterViewInit, OnDestroy {
  kind = input.required<string>();
  prs = input<MergedPr[]>([]);
  /** STEPS: the stage labels; the last one can be wired to the live health check. */
  labels = input<string[]>([]);
  caption = input('');
  liveLast = input(false);
  compact = input(false);
  /** TENURE: "Aug 2022 – May 2023" or "Sep 2026 – Present", scaled against maxMonths. */
  period = input('');
  maxMonths = input(24);
  readonly live = inject(LiveStatus);
  private readonly el = inject(ElementRef<HTMLElement>);
  private readonly browser = isPlatformBrowser(inject(PLATFORM_ID));
  readonly calm = this.browser && !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

  playing = signal(false);
  testCount = signal(0);
  private io?: IntersectionObserver;
  private countTimer?: ReturnType<typeof setInterval>;

  readonly apps = ['FastAPI', 'Angular', 'React', 'HTML'];
  readonly commands = ['kubectl rollout undo', 'pg_cancel_backend(pid)', 'systemctl restart nginx'];
  readonly gates = ['G1', 'G2', 'G3', 'G4', 'G5'];
  readonly tests = Array.from({ length: 637 }, (_, i) => i);
  readonly nodes = [
    { x: 14, y: 32, l: 'plan' }, { x: 92, y: 10, l: 'agent' }, { x: 92, y: 32, l: 'agent' }, { x: 92, y: 54, l: 'agent' },
    { x: 170, y: 32, l: 'merge' }, { x: 230, y: 32, l: 'human' }, { x: 288, y: 32, l: 'out' },
  ].map((n, i) => ({ ...n, l: n.l === 'agent' ? `agent ${i}` : n.l }));
  readonly edges = [
    'M21 32 L85 10', 'M21 32 L85 32', 'M21 32 L85 54',
    'M99 10 L163 32', 'M99 32 L163 32', 'M99 54 L163 32',
    'M177 32 L223 32', 'M237 32 L281 32',
  ];

  merges = computed(() => this.prs());

  readonly loopLabels = ['think', 'tool', 'observe', 'answer'];
  readonly loopPos = [{ x: 150, y: 10 }, { x: 262, y: 32 }, { x: 150, y: 54 }, { x: 38, y: 32 }];
  readonly inputs = [
    { t: 'summarise this incident', v: '✓ pass', k: 'ok' },
    { t: 'ignore previous instructions…', v: '✗ blocked', k: 'bad' },
    { t: 'my aadhaar is 4321 …', v: '◐ PII masked', k: 'pii' },
  ];

  steps = computed(() => {
    const labels = this.labels(), n = Math.max(labels.length, 1), gap = 10;
    const w = (300 - gap * (n - 1)) / n;
    const y = this.compact() ? 15 : 32;
    return { labels, w, gap, h: this.compact() ? 18 : 24, y, path: `path('M${w / 2} ${y} H${300 - w / 2}')` };
  });
  cap = computed(() => {
    if (this.kind() === 'STEPS' && this.liveLast()) {
      const s = this.live.apiState();
      return s === 'ok' ? `${this.caption()} · live API ${this.live.apiMs()} ms` : `${this.caption()} · ${s === 'checking' ? 'checking the live API…' : 'live API not answering'}`;
    }
    return this.caption();
  });

  months = computed(() => {
    const order: string[] = [];
    const by = new Map<string, Map<string, number>>();
    for (const m of [...this.prs()].reverse()) {
      const key = (m as any).merged as string;
      if (!key) continue;
      if (!by.has(key)) { by.set(key, new Map()); order.push(key); }
      const r = by.get(key)!; r.set(m.repo, (r.get(m.repo) ?? 0) + 1);
    }
    const toDate = (k: string) => new Date(`1 ${k}`).getTime();
    return order.sort((a, b) => toDate(a) - toDate(b)).map(label => {
      const segs = [...by.get(label)!.entries()].map(([repo, n]) => ({ repo, n }));
      return { label, segs, total: segs.reduce((a, b) => a + b.n, 0) };
    });
  });
  monthMax = computed(() => Math.max(1, ...this.months().map(m => m.total)));

  tenure = computed(() => {
    const [a, b] = this.period().split(/\s+[–-]\s+/);
    const parse = (x: string) => { const d = new Date(`1 ${x}`); return isNaN(d.getTime()) ? null : d; };
    const start = parse(a ?? ''), present = /present/i.test(b ?? '');
    const end = present ? new Date() : parse(b ?? '');
    if (!start || !end) return null;
    const months = Math.max(1, (end.getFullYear() - start.getFullYear()) * 12 + end.getMonth() - start.getMonth());
    const y = Math.floor(months / 12), mo = months % 12;
    const label = [y ? `${y} yr` : '', mo ? `${mo} mo` : ''].filter(Boolean).join(' ');
    return { pct: Math.min(100, (months / this.maxMonths()) * 100), label, present };
  });
  shippedCap = computed(() => {
    switch (this.live.apiState()) {
      case 'ok': return `heartbeat from the live API · ${this.live.apiMs()} ms`;
      case 'slow': return 'live API waking up';
      case 'down': return 'live API not answering right now';
      default: return 'checking the live API…';
    }
  });

  color(repo: string) { return REPO_COLOR[repo] ?? '#86BC25'; }

  ngAfterViewInit() {
    if (!this.browser) return;
    this.live.start();
    if (this.calm || !('IntersectionObserver' in window)) { this.playing.set(true); this.testCount.set(637); return; }
    this.io = new IntersectionObserver(([e]) => {
      this.playing.set(e.isIntersecting);
      if (this.kind() === 'RELIABLE') e.isIntersecting ? this.runTests() : this.stopTests();
    }, { threshold: 0.35 });
    this.io.observe(this.el.nativeElement);
  }

  ngOnDestroy() { this.io?.disconnect(); this.stopTests(); }

  /** The counter follows the dots: 637 tests in about 3.8 s. */
  private runTests() {
    this.stopTests();
    this.testCount.set(0);
    const t0 = performance.now();
    this.countTimer = setInterval(() => {
      const n = Math.min(637, Math.round(((performance.now() - t0) / 3822) * 637));
      this.testCount.set(n);
      if (n >= 637) this.stopTests();
    }, 60);
  }
  private stopTests() { clearInterval(this.countTimer); }
}
