import { AfterViewInit, Component, ElementRef, OnDestroy, PLATFORM_ID, computed, inject, input, signal } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { LiveStatus } from './live-status.service';

/**
 * Each Engineering Proof card acts out its own claim: the LIVE card beats with the
 * real health check, the 66 card is one square per merged PR, the tests card runs
 * 637 dots green, and so on. Animations only play while the card is on screen.
 */
export interface MergedPr { repo: string; title: string; pr: string; }

const REPO_COLOR: Record<string, string> = {
  'py-pdf/pypdf': '#86BC25', 'joblib/joblib': '#62B5E5', 'UKPLab/sentence-transformers': '#FFB81C',
  'huggingface/sentence-transformers': '#FFB81C', 'nltk/nltk': '#00ABAB', 'authlib/authlib': '#C084FC',
};

@Component({
  selector: 'proof-viz',
  standalone: true,
  host: { '[class.play]': 'playing()', '[class.calm]': 'calm' },
  template: `
    @switch (kind()) {
      @case ('SHIPPED') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <line x1="0" y1="40" x2="300" y2="40" class="pv-grid"/>
          <path class="pv-ekg" [class.down]="live.apiState() === 'down'" pathLength="1"
                d="M0 40 H70 L80 40 L88 22 L96 56 L104 10 L112 46 L120 40 H190 L200 40 L208 22 L216 56 L224 10 L232 46 L240 40 H300"/>
          <circle class="pv-beat" r="4" cy="40" [class.down]="live.apiState() === 'down'"/>
        </svg>
        <span class="pv-cap">{{ shippedCap() }}</span>
      }
      @case ('INTEGRATED') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          @for (a of apps; track a; let i = $index) {
            <text [attr.x]="0" [attr.y]="11 + i * 15" class="pv-lbl">{{ a }}</text>
            <path [attr.d]="'M58 ' + (7 + i * 15) + ' C150 ' + (7 + i * 15) + ' 170 32 232 32'" class="pv-wire"/>
            <circle r="2.6" class="pv-packet" [style.offset-path]="'path(\\'M58 ' + (7 + i * 15) + ' C150 ' + (7 + i * 15) + ' 170 32 232 32\\')'" [style.animation-delay]="i * 0.35 + 's'"/>
          }
          <rect x="232" y="18" width="66" height="28" rx="4" class="pv-hub"/>
          <text x="265" y="36" text-anchor="middle" class="pv-hub-t">1 engine</text>
        </svg>
      }
      @case ('TRUSTED') {
        <div class="pv-squares" role="list" aria-label="One square per merged pull request">
          @for (m of merges(); track m.pr; let i = $index) {
            <a role="listitem" class="pv-sq" [href]="m.pr" target="_blank" rel="noopener" [title]="m.repo + ': ' + m.title"
               [style.background]="color(m.repo)" [style.animation-delay]="i * 18 + 'ms'"></a>
          }
        </div>
        <span class="pv-cap">one square per merged PR · hover one</span>
      }
      @case ('FAST') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <text x="0" y="17" class="pv-lbl">before</text>
          <rect x="44" y="9" width="246" height="11" rx="2" class="pv-track"/>
          <rect x="44" y="9" width="246" height="11" rx="2" class="pv-bar slow"/>
          <text x="0" y="47" class="pv-lbl">after</text>
          <rect x="44" y="39" width="246" height="11" rx="2" class="pv-track"/>
          <rect x="44" y="39" width="246" height="11" rx="2" class="pv-bar fast"/>
        </svg>
        <span class="pv-cap">same request · 78 s before, 4 s after</span>
      }
      @case ('AFFORDABLE') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <text x="0" y="17" class="pv-lbl">GPT-4o</text>
          <rect x="52" y="9" width="238" height="11" rx="2" class="pv-bar cost-hi"/>
          <text x="0" y="47" class="pv-lbl">mine</text>
          <rect x="52" y="39" width="3" height="11" rx="1" class="pv-bar cost-lo"/>
          <text x="62" y="48" class="pv-note">÷ 500</text>
        </svg>
      }
      @case ('SAFE') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <rect x="0" y="16" width="52" height="32" rx="4" class="pv-hub"/>
          <text x="26" y="36" text-anchor="middle" class="pv-hub-t">SQL</text>
          @for (c of commands; track c; let i = $index) {
            <g class="pv-cmd" [style.animation-delay]="i * 1.1 + 's'">
              <text x="64" [attr.y]="14 + i * 19" class="pv-code">{{ c }}</text>
              <text x="296" [attr.y]="14 + i * 19" text-anchor="end" class="pv-ok">✓ verbatim</text>
            </g>
          }
        </svg>
        <span class="pv-cap">example runbook commands · generated by the model: 0</span>
      }
      @case ('SECURE') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          <line x1="8" y1="30" x2="292" y2="30" class="pv-wire"/>
          @for (g of gates; track g; let i = $index) {
            <g class="pv-gate" [style.animation-delay]="0.5 + i * 0.5 + 's'">
              <rect [attr.x]="34 + i * 54" y="16" width="20" height="28" rx="3"/>
              <text [attr.x]="44 + i * 54" y="58" text-anchor="middle" class="pv-lbl">{{ g }}</text>
            </g>
          }
          <circle r="4" cy="30" class="pv-req"/>
          <circle r="4" cy="30" class="pv-bad"/>
        </svg>
        <span class="pv-cap">every response passes 5 gates · injections stop at G2</span>
      }
      @case ('RELIABLE') {
        <div class="pv-tests" aria-hidden="true">
          @for (t of tests; track t) { <i [style.animation-delay]="t * 6 + 'ms'"></i> }
        </div>
        <span class="pv-cap pv-count">{{ testCount() }} passed{{ testCount() === 637 ? ' · under 4 s' : '' }}</span>
      }
      @case ('ORCHESTRATED') {
        <svg viewBox="0 0 300 64" class="pv" aria-hidden="true">
          @for (e of edges; track $index; let i = $index) {
            <path [attr.d]="e" class="pv-wire"/>
            <circle r="2.4" class="pv-packet" [style.offset-path]="'path(\\'' + e + '\\')'" [style.animation-delay]="(i % 3) * 0.25 + (i > 5 ? 1 : i > 2 ? 0.6 : 0) + 's'"/>
          }
          @for (n of nodes; track n.l) {
            <circle [attr.cx]="n.x" [attr.cy]="n.y" r="7" class="pv-node" [class.human]="n.l === 'human'"/>
            @if (!n.l.startsWith('agent')) { <text [attr.x]="n.x" [attr.y]="n.y + 19" text-anchor="middle" class="pv-lbl">{{ n.l }}</text> }
          }
        </svg>
        <span class="pv-cap">plan → 3 agents in parallel → merge → human approval → out</span>
      }
    }
  `,
  styleUrl: './proof-viz.scss',
})
export class ProofViz implements AfterViewInit, OnDestroy {
  kind = input.required<string>();
  prs = input<MergedPr[]>([]);
  readonly live = inject(LiveStatus);
  private readonly el = inject(ElementRef<HTMLElement>);
  private readonly browser = isPlatformBrowser(inject(PLATFORM_ID));
  readonly calm = this.browser && !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

  playing = signal(false);
  testCount = signal(0);
  private io?: IntersectionObserver;
  private countTimer?: ReturnType<typeof setInterval>;

  readonly apps = ['FastAPI', 'Angular', 'React', 'HTML'];
  readonly commands = ['kubectl rollout undo', 'pg_cancel_backend(pid)', 'systemctl restart nginx'];
  readonly gates = ['G1', 'G2', 'G3', 'G4', 'G5'];
  readonly tests = Array.from({ length: 637 }, (_, i) => i);
  readonly nodes = [
    { x: 14, y: 32, l: 'plan' }, { x: 92, y: 10, l: 'agent' }, { x: 92, y: 32, l: 'agent' }, { x: 92, y: 54, l: 'agent' },
    { x: 170, y: 32, l: 'merge' }, { x: 230, y: 32, l: 'human' }, { x: 288, y: 32, l: 'out' },
  ].map((n, i) => ({ ...n, l: n.l === 'agent' ? `agent ${i}` : n.l }));
  readonly edges = [
    'M21 32 L85 10', 'M21 32 L85 32', 'M21 32 L85 54',
    'M99 10 L163 32', 'M99 32 L163 32', 'M99 54 L163 32',
    'M177 32 L223 32', 'M237 32 L281 32',
  ];

  merges = computed(() => this.prs());
  shippedCap = computed(() => {
    switch (this.live.apiState()) {
      case 'ok': return `heartbeat from the live API · ${this.live.apiMs()} ms`;
      case 'slow': return 'live API waking up';
      case 'down': return 'live API not answering right now';
      default: return 'checking the live API…';
    }
  });

  color(repo: string) { return REPO_COLOR[repo] ?? '#86BC25'; }

  ngAfterViewInit() {
    if (!this.browser) return;
    this.live.start();
    if (this.calm || !('IntersectionObserver' in window)) { this.playing.set(true); this.testCount.set(637); return; }
    this.io = new IntersectionObserver(([e]) => {
      this.playing.set(e.isIntersecting);
      if (this.kind() === 'RELIABLE') e.isIntersecting ? this.runTests() : this.stopTests();
    }, { threshold: 0.35 });
    this.io.observe(this.el.nativeElement);
  }

  ngOnDestroy() { this.io?.disconnect(); this.stopTests(); }

  /** The counter follows the dots: 637 tests in about 3.8 s. */
  private runTests() {
    this.stopTests();
    this.testCount.set(0);
    const t0 = performance.now();
    this.countTimer = setInterval(() => {
      const n = Math.min(637, Math.round(((performance.now() - t0) / 3822) * 637));
      this.testCount.set(n);
      if (n >= 637) this.stopTests();
    }, 60);
  }
  private stopTests() { clearInterval(this.countTimer); }
}
